---
title: "Group 1 Project 2 Report"
author: "Becky Desrosiers"
date: "2023-11-19"
output: html_document
---


# Section 1: High-level summary













# Section 2: Description of data and variables











# Section 3: Questions of interest


### Question 1: What factors affect the price of a home? Out of all the predictors, which is the best model? Bedrooms, bathrooms, square footage of the house or the property, condition, square footage of above-floor-level space, square footage of basement space, year built, year renovated, and the square footage of the houses and properties of the 15 closest neighbors.

### Question 2: Can we predict whether a house is on a waterfront based on other qualities? Square footage, # bedrooms, # bathrooms, sqft_living15, condition, grade.


The response variable for the first question will be price. We are interested in finding which factors most influence the price. The response variable for the second data set is waterfront status: is it a waterfront property or not? We are interested in predicting whether a property is waterfront or not based on other attributes.


The practical application for the first question will be for a construction company to determine how best to invest their money into a project so that they can sell it for the best price. A buyer may also benefit from the analysis by discerning which attributes can be money-savers vs. with which attributes (number of bathrooms, number of floors, etc.) they may be able to gain more without spending much more.


We are interested in the second question to find out if there is a significant difference between waterfront properties and non-waterfront properties. We hypothesize that waterfront properties will be higher quality in general (higher square footage, more bedrooms and bathrooms, higher grade), and have neighbors with bigger houses, but perhaps will be in worse condition because of the proximity to water and the risk of flooding.












```{r}
# Setup
library(ggplot2)
library(dplyr)

# Split data
Data <- read.csv("../Instructions/kc_house_data.csv", sep=",", header=TRUE) %>% 
  # remove irrelevant data: id, date, zip code, latitude and longitude
  select(-1, -2, -17, -18, -19)

set.seed(6021)

sample.data <- sample.int(nrow(Data), floor(.50*nrow(Data)), replace = F)
train <- Data[sample.data, ]
test <- Data[-sample.data, ]
```


# Section 4: Question 1 data visualizations













# Section 5: Question 1 linear regression


















# Section 6: Question 2 data visualizations


















# Section 7: Question 2 logistic regression

























